# Generated by Django 5.1.7 on 2025-04-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='key_art',
            field=models.ImageField(blank=True, default='forum/images/placeholder.svg', null=True, upload_to='forum_images/'),
        ),
    ]
